.TH BUS-BROADCAST 1 BUS
.SH NAME
bus broadcast - Broadcast a message on a bus
.SH SYNOPSIS
.B bus broadcast
[-n]
.IR pathname
.IR message
.SH DESCRIPTION
Broadcast \fImessage\fP on the bus associated with \fIpathname\fP.
.SH OPTIONS
.TP
.B \-n
Fail if another process is attempting to broadcast on the bus.
.SH EXIT STATUS
.TP
0
The command was successful.
.TP
1
The command failed.
.TP
2
The command is not recognised.
.SH SEE ALSO
.BR bus (5)
