.TH BUS-WAIT 1 BUS
.SH NAME
bus wait - Listen for a new message on a bus
.SH SYNOPSIS
.B bus wait
.IR pathname
.IR command
.SH DESCRIPTION
Listen for a new message on the bus associated with \fIpathname\fP, stop
listening once a message has been received.  Once a message is received,
\fIcommand\fP will be spawned with \fI$msg\fP set to the received
message.  POSIX shell syntax applies to \fIcommand\fP.
.SH EXIT STATUS
.TP
0
The command was successful.
.TP
1
The command failed.
.TP
2
The command is not recognised.
.SH SEE ALSO
.BR bus (5)
