.TH BUS-REMOVE 1 BUS-%VERSION%
.SH NAME
bus remove - Remove a bus
.SH SYNOPSIS
.B bus remove
[--]
.IR pathname
.SH DESCRIPTION
Remove the bus associated with \fIpathname\fP.
.SH EXIT STATUS
.TP
0
The command was successful.
.TP
1
The command failed.
.TP
2
The command is not recognised.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
Please report bugs to https://github.com/maandree/bus/issues or to
maandree@member.fsf.org
