.TH BUS-LISTEN 1 BUS-%VERSION%
.SH NAME
bus listen - Listen for new messages on a bus
.SH SYNOPSIS
.B bus listen
[--]
.IR pathname
.IR command
.SH DESCRIPTION
Listen for new messages on the bus associated with \fIpathname\fP.  Once
a message is received, \fIcommand\fP will be spawned with \fI$msg\fP set
to the received message.  POSIX shell syntax applies to \fIcommand\fP.
.SH EXIT STATUS
.TP
0
The command was successful.
.TP
1
The command failed.
.TP
2
The command is not recognised.
.SH SEE ALSO
bus(5)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH LICENSE
MIT/X Consortium License.
.SH BUGS
Please report bugs to https://github.com/maandree/bus/issues or to
maandree@member.fsf.org
