.TH BUS_UNLINK 3 BUS-%VERSION%
.SH NAME
bus_unlink - Remove a bus
.SH SYNOPSIS
.LP
.nf
#include <bus.h>
.P
int bus_unlink(const char *\fIfile\fP);
.fi
.SH DESCRIPTION
The
.BR bus_unlink ()
function removes the bus assoicated with the pathname stored in
\fIfile\fP.  The function also unlinks the file.
.SH RETURN VALUES
Upon successful completion, the function returns 0.  Otherwise the
function returns -1 and sets \fIerrno\fP to indicate the error.
.SH ERRORS
.TP
.B EINVAL
The bus does not exist.
.TP
.B EACCES
Operation permission is denied to the calling process.
.TP
.B EPERM
The user does not have permission to remove the bus.
.PP
The
.BR bus_unlink (3)
function may also fail and set \fIerrno\fP to any of the errors
specified for the routines
.BR unlink (2),
.BR open (2),
.BR semget (3)
and
.BR shmget (3).
.SH SEE ALSO
.BR bus-create (1),
.BR bus (5),
.BR libbus (7),
.BR bus_create (3),
.BR bus_close (3),
.BR unlink (2),
.BR open (2),
.BR semget (3),
.BR shmget (3)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH LICENSE
MIT/X Consortium License.
.SH BUGS
Please report bugs to https://github.com/maandree/bus/issues or to
maandree@member.fsf.org
